#include "Managers.h"
#include "AssetManager.h"
#include "physics/PhysicsManager.h"
#include "network/NetworkManager.h"
#include "render/RenderManager.h"
#include "entity/EntityManager.h"
#include "sound/SoundManager.h"
#include "InputManager.h"
#include "event/EventManager.h"
#include "level/LevelManager.h"

RenderManager gRenderManager;
EntityManager gEntityManager;
NetworkManager gNetworkManager;
PhysicsManager gPhysicsManager;
SoundManager gSoundManager;
AssetManager gAssetManager;
InputManager gInputManager;
EventManager gEventManager;
LevelManager gLevelManager;